### ISSUE TITLE
svg icons

### ISSUE THREAD

**Issue by jfrausto** [jfrausto/cryptick#14]
render icons for each crypto currency. Could be svg's so we can manipulate them with styling and framer-motion.
mentioned finding a svg converter/generator.

**Comment by JOCECODE** [comment]
Here are some resources that I found that could help with the icons

**CRYPTOCURRENCY ICONS**
https://cryptologos.cc/

**FILE CONVERTOR**
https://www.aconvert.com/

**Comment by JOCECODE** [comment]
I made recent commits to a new branch **_addSVGIcons_**

-  Deleted whatsyoname.tsx page not needed
-  Added conditional rendering on line 89 ChooseCrypto.tsx to fix CGDL to CELO 
- Added icons folder into public folder



**Ampleforth (AMPL) cryptick is showing FORTH on Coinbase they are showing Ample forth 
Governance token (FORTH) I believe it is not a typo 
ETH ( I am assuming that it is ethereum it can also be a typo for Ether Zero ETZ )**



**larger than most icons**
ZRX 
STORJ
BAT



**smaller than most icons**
RLC
BNT
 
There is one icon that I missed I have 68 icons but one is a no name icon 



The icons have a similar pattern on their filename

bitcoin-_**btc-icon**_
dogecoin-**_doge-icon_**


Random thought 
I am thinking if we can render it somehow like down below just thought of this
 return <ChooseCryptoCard
                key={data.tickerName}
                tickerName={(data.tickerName)}
                fullName={data.fullName}
(if something like this works would be dope lmao)                
img={"${data.tickerName}-logo"}             
/>
             <img src={"**${data.tickerName}**-logo"} alt="iconname" height="32px" width="32px"/>
