### ISSUE TITLE
Infinite loop get Request

### ISSUE THREAD

**Issue by JOCECODE** [jfrausto/cryptick#3]
I am currently working on trying to display the crypto information using Axios as the get request npm package. I am running into the issue of making it a request only one time. Also, I need to be able to display it. I am not using an API key because this is only to get the information. The URL I am using is "https://api.pro.coinbase.com/products" which then returns an Array of the crypto (it's like 183). 
Any suggestions on different get requests. I remember we used Axios in school but don't remember when specifically.

Questions?
How should I approach the get request is there any other ways y'all do it to get it(Ajax perhaps)?
Is anyone comfortable with the map method?
Any ideas on displaying the information I figure a component that maps each of the objects in the array and create or insert into divs to hold them.

Troubleshooting
fatal process out of memory zone

Solution: I stopped the server closed it and VsCode and restarted it. Most likely I am assuming it is the infinite get request I had going on.

**Comment by jfrausto** [comment]
we could use an async function with `await fetch` perhaps

**Comment by JOCECODE** [comment]
Def the docs on Axios show how to use the await and fetch. I think also I need to set up the component to use useEffect and the useRef too. I am thinking it needs a state but def want to check out useRef more (not comfortable with it).

**Comment by JOCECODE** [comment]
Created an api call that occurs once and puts the data on the page. It may or may not be information that we need but the link can be changed. It is working as intended so I am closing this issue.
